global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics for all nodes
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - 'pistor0:9100'
          - 'pistor1:9100'
          - 'pistor2:9100'

  # cAdvisor - Container metrics for all nodes
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'pistor0:8080'
          - 'pistor1:8080'
          - 'pistor2:8080'

  # Docker Swarm service discovery
  - job_name: 'docker-swarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: ${1}:9100

  # Docker container exporter
  - job_name: 'docker-exporter'
    static_configs:
      - targets:
          - 'pistor0:9104'
          - 'pistor1:9104'
          - 'pistor2:9104'

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
