version: '3.8'

services:
  komga:
    image: gotson/komga:latest
    ports:
      - "8081:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx1g
      - KOMGA_CONFIGDIR=/config
      - TZ=UTC
    volumes:
      - /data/komga/config:/config
      - /data/komga/data:/data
      - /data/komga/library:/library:ro
    networks:
      - cluster-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.komga.rule=Host(`komga.local`)"
        - "traefik.http.services.komga.loadbalancer.server.port=8080"
        - "traefik.docker.network=cluster-network"

networks:
  cluster-network:
    external: true
